# Generated by Django 5.0.6 on 2024-06-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='otp',
            field=models.IntegerField(default=1111),
        ),
    ]
