# Generated by Django 5.0.6 on 2024-06-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_register_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='otp',
            field=models.IntegerField(),
        ),
    ]
