# Generated by Django 5.0.6 on 2024-06-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(blank=True, choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegetables')], max_length=30, null=True),
        ),
    ]
