# Generated by Django 5.0.6 on 2024-06-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_categorie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
