# Generated by Django 5.0.6 on 2024-06-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
