# Generated by Django 5.0.6 on 2024-07-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_register_address_alter_register_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
