# Generated by Django 5.0.6 on 2024-07-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_register_address_alter_register_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
