# Generated by Django 5.0.6 on 2024-07-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_register_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.IntegerField(blank=True, default=1234567890, null=True),
        ),
    ]
