# Generated by Django 5.0.6 on 2024-07-13 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_register_cartitem_user_id_order_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
    ]
