# Generated by Django 5.0.6 on 2024-07-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_register_address_alter_register_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
