# Generated by Django 5.0.6 on 2024-07-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_register_address_alter_register_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
