# Generated by Django 5.0.6 on 2024-07-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_register_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='halfrating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
